const $ = selector => document.querySelector(selector);
const state = { user:null, csrf:'', workspaces:[], workspace:null, projects:[], project:null, pages:[] };
const themeMedia=window.matchMedia('(prefers-color-scheme: dark)');
let themeMode=localStorage.getItem('pages-theme')||'system';
function applyTheme(mode,save=true){themeMode=['light','dark','system'].includes(mode)?mode:'system';const effective=themeMode==='system'?(themeMedia.matches?'dark':'light'):themeMode;document.documentElement.dataset.theme=effective;document.documentElement.dataset.themeMode=themeMode;if(save)localStorage.setItem('pages-theme',themeMode);document.querySelectorAll('[data-theme-choice]').forEach(button=>button.classList.toggle('active',button.dataset.themeChoice===themeMode));const authTheme=$('#auth-theme');if(authTheme){authTheme.textContent=effective==='dark'?'☾':'☀';authTheme.title=`当前${effective==='dark'?'深色':'浅色'}，点击切换`;}}
applyTheme(themeMode,false);themeMedia.addEventListener?.('change',()=>{if(themeMode==='system')applyTheme('system',false);});
const esc = (value='') => String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const slugify = value => value.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,63);
const pageEndpoint = () => `/api/workspaces/${state.workspace.slug}/projects/${state.project.slug}/pages`;

async function api(path,options={}){
  const headers={...(options.json?{'Content-Type':'application/json'}:{}),...(state.csrf?{'X-CSRF-Token':state.csrf}:{}),...(options.headers||{})};
  const response=await fetch(path,{...options,headers});
  if(response.status===204)return null;
  const data=await response.json().catch(()=>({}));
  if(response.status===401&&state.user){showAuth(false);throw new Error('登录已过期，请重新登录');}
  if(!response.ok)throw new Error(data.error?.message||`请求失败 (${response.status})`);
  return data;
}

async function init(){
  try{const me=await api('/api/auth/me');signedIn(me);}catch{const status=await api('/api/auth/setup-status');showAuth(status.needsSetup);}
  fetch('/healthz').then(r=>{if(r.ok){$('#health').classList.add('ok');$('#health').lastChild.textContent='服务正常';}}).catch(()=>{});
}

function showAuth(setup){
  state.user=null;state.csrf='';$('#auth-screen').hidden=false;$('.sidebar').hidden=true;
  $('#auth-title').textContent=setup?'创建平台管理员':'欢迎回来';
  $('#auth-copy').textContent=setup?'第一次使用 Pages，请创建管理员账号。':'登录你的团队空间，继续发布精彩页面。';
  $('#setup-fields').hidden=!setup;$('#auth-submit').textContent=setup?'创建并进入 Pages':'登录';
  $('#auth-form').dataset.setup=String(setup);$('#auth-error').textContent='';
}

function signedIn(data){
  state.user=data.user;state.csrf=data.csrfToken;$('#auth-screen').hidden=true;$('.sidebar').hidden=false;
  $('#user-name').textContent=state.user.name;$('#user-avatar').textContent=state.user.name.slice(0,1).toUpperCase();$('#user-role').textContent=state.user.role==='platform_admin'?'平台管理员':'平台成员';$('#admin-nav').hidden=state.user.role!=='platform_admin';$('#new-workspace').hidden=false;loadWorkspaces();
}
function syncWorkspaceTools(){const canAdmin=!!state.workspace&&(state.user?.role==='platform_admin'||['owner','admin'].includes(state.workspace.currentRole));$('#workspace-tools').hidden=!canAdmin;}

$('#auth-form').onsubmit=async event=>{
  event.preventDefault();const form=new FormData(event.currentTarget),setup=event.currentTarget.dataset.setup==='true';$('#auth-submit').disabled=true;$('#auth-error').textContent='';
  try{const body={username:form.get('username'),password:form.get('password')};if(setup)Object.assign(body,{name:form.get('name'),email:form.get('email')});const data=await api(setup?'/api/auth/setup':'/api/auth/login',{method:'POST',json:true,body:JSON.stringify(body)});signedIn(data);}
  catch(error){$('#auth-error').textContent=error.message;}finally{$('#auth-submit').disabled=false;}
};

$('#logout').onclick=async()=>{try{await api('/api/auth/logout',{method:'POST'});}finally{showAuth(false);}};
document.querySelectorAll('[data-theme-choice]').forEach(button=>button.onclick=()=>applyTheme(button.dataset.themeChoice));
$('#auth-theme').onclick=()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');

async function loadWorkspaces(){
  const nav=$('#workspaces');nav.innerHTML='<span class="muted">正在载入…</span>';
  try{const data=await api('/api/workspaces');state.workspaces=data.workspaces;if(state.workspace&&!state.workspaces.some(w=>w.slug===state.workspace.slug))state.workspace=null;if(!state.workspace&&state.workspaces.length)state.workspace=state.workspaces[0];renderWorkspaces();if(state.workspace)await loadProjects(false);else showEmpty();}
  catch(error){nav.innerHTML=`<span class="muted">${esc(error.message)}</span>`;showEmpty();}
}

function renderWorkspaces(){
  const nav=$('#workspaces');nav.innerHTML='';if(!state.workspaces.length){nav.innerHTML='<span class="muted">还没有工作空间</span>';return;}
  const canSortWorkspaces=state.user?.role==='platform_admin';
  for(const workspace of state.workspaces){const section=document.createElement('section');section.className=`workspace ${state.workspace?.slug===workspace.slug?'active':''}`;section.dataset.sortId=workspace.slug;section.draggable=canSortWorkspaces;const button=document.createElement('button');button.textContent=workspace.name;if(canSortWorkspaces){const handle=document.createElement('span');handle.className='drag-handle';handle.textContent='⠿';handle.title='拖拽调整工作空间顺序';button.prepend(handle);}button.onclick=async()=>{state.workspace=workspace;state.project=null;renderWorkspaces();await loadProjects(false);};section.append(button);if(state.workspace?.slug===workspace.slug){const projects=document.createElement('div');projects.className='projects';const canSortProjects=state.user.role==='platform_admin'||['owner','admin'].includes(workspace.currentRole);for(const project of state.projects){const item=document.createElement('button');item.dataset.sortId=project.slug;item.draggable=canSortProjects;item.textContent=project.name;if(canSortProjects){const handle=document.createElement('span');handle.className='drag-handle project-handle';handle.textContent='⠿';handle.title='拖拽调整项目顺序';item.prepend(handle);}item.className=state.project?.slug===project.slug?'active':'';item.onclick=()=>selectProject(project);projects.append(item);}section.append(projects);if(canSortProjects)enableSortable(projects,'.projects > button',async slugs=>{await api(`/api/workspaces/${workspace.slug}/projects/order`,{method:'PUT',json:true,body:JSON.stringify({slugs})});state.projects.sort((a,b)=>slugs.indexOf(a.slug)-slugs.indexOf(b.slug));});}nav.append(section);}
  if(canSortWorkspaces)enableSortable(nav,'.workspace',async slugs=>{await api('/api/workspaces/order',{method:'PUT',json:true,body:JSON.stringify({slugs})});state.workspaces.sort((a,b)=>slugs.indexOf(a.slug)-slugs.indexOf(b.slug));});
}

function enableSortable(container,selector,onSave){let dragged=null;const items=()=>[...container.querySelectorAll(selector)].filter(item=>item.parentElement===container);for(const item of items()){item.addEventListener('dragstart',event=>{dragged=item;item.classList.add('dragging');event.dataTransfer.effectAllowed='move';});item.addEventListener('dragend',async()=>{if(!dragged)return;dragged.classList.remove('dragging');dragged=null;container.classList.remove('sorting');try{await onSave(items().map(node=>node.dataset.sortId));}catch(error){alert(`排序保存失败：${error.message}`);await loadWorkspaces();}});}container.addEventListener('dragover',event=>{event.preventDefault();if(!dragged)return;container.classList.add('sorting');const target=event.target.closest(selector);if(!target||target===dragged||target.parentElement!==container)return;const rect=target.getBoundingClientRect();container.insertBefore(dragged,event.clientY<rect.top+rect.height/2?target:target.nextSibling);});}

async function loadProjects(autoSelect=true){syncWorkspaceTools();try{const data=await api(`/api/workspaces/${state.workspace.slug}/projects`);state.projects=data.projects;if(state.project&&!state.projects.some(p=>p.slug===state.project.slug))state.project=null;if(autoSelect&&!state.project&&state.projects.length)state.project=state.projects[0];renderWorkspaces();if(state.project)await selectProject(state.project);else showEmpty(true);}catch(error){state.projects=[];renderWorkspaces();showEmpty(true,error.message);}}
function showProductView(){ $('#management-view').hidden=true;$('#main-topbar').hidden=false;document.querySelectorAll('.nav-button').forEach(button=>button.classList.remove('active')); }
async function selectProject(project){showProductView();state.project=project;renderWorkspaces();const canAdmin=state.user.role==='platform_admin'||['owner','admin'].includes(state.workspace.currentRole),canWrite=canAdmin||state.workspace.currentRole==='editor';$('#workspace-slug').textContent=state.workspace.slug;$('#project-slug').textContent=project.slug;$('#project-name').textContent=project.name;$('#project-description').textContent=project.description||'发布和管理这个项目中的页面。';$('#empty-state').hidden=true;$('#project-view').hidden=false;$('.publish-panel').hidden=!canWrite;$('#workspace-members').hidden=!canAdmin;$('#new-project').hidden=!canAdmin;await loadPages();}
function showEmpty(hasWorkspace=false,error=''){showProductView();syncWorkspaceTools();state.project=null;$('#project-view').hidden=true;$('#empty-state').hidden=false;$('#workspace-slug').textContent=state.workspace?.slug||'工作空间';$('#project-slug').textContent='首页';const canAdmin=!!state.workspace&&(state.user.role==='platform_admin'||['owner','admin'].includes(state.workspace.currentRole));$('#new-project').hidden=!canAdmin;if(hasWorkspace&&state.workspace){$('#project-name').textContent=state.workspace.name;$('#project-description').textContent=error||`欢迎回到 ${state.workspace.name}，从这里了解发布流程并进入项目。`;renderWorkspaceHome(canAdmin,error);}else{$('#project-name').textContent='开始使用 Pages';$('#project-description').textContent=error||'创建或加入工作空间，然后开始发布页面。';$('#home-title').textContent='让每个想法，都有一个可访问的页面。';$('#home-copy').textContent='创建工作空间和项目，通过安全预览把 AI 生成内容正式发布。';$('#home-project-list').innerHTML='<div class="home-empty">还没有可访问的工作空间</div>';$('#home-api-example').textContent='创建工作空间后即可获得 API 接入地址';}}
function renderWorkspaceHome(canAdmin,error=''){const role=state.workspace.currentRole==='platform_admin'?'平台管理员':roleName(state.workspace.currentRole);$('#home-title').textContent=`欢迎回到 ${state.workspace.name}`;$('#home-copy').textContent=error||`你以${role}身份访问此空间。按照下方流程，将 AI 生成内容安全地变成正式页面。`;$('#home-api-example').textContent=`POST /api/workspaces/${state.workspace.slug}/projects/{project}/pages`;const list=$('#home-project-list');list.innerHTML=state.projects.length?'':'<div class="home-empty">还没有项目，从创建第一个项目开始。</div>';for(const project of state.projects.slice(0,6)){const item=document.createElement('div');item.className='home-project';item.innerHTML=`<div><strong>${esc(project.name)}</strong><small>${esc(project.description||project.slug)} · ${new Date(project.updatedAt).toLocaleDateString()}</small></div><span>→</span>`;item.onclick=()=>selectProject(project);list.append(item);}$('#home-new-project').hidden=!canAdmin;}

async function loadPages(){const root=$('#pages');root.innerHTML='<div class="empty">正在载入页面…</div>';try{const data=await api(pageEndpoint());state.pages=data.pages;renderPages();}catch(error){root.innerHTML=`<div class="empty error">${esc(error.message)}</div>`;}}
function renderPages(){$('#page-count').textContent=state.pages.length;$('#last-updated').textContent=state.pages.length?new Date(state.pages[0].updatedAt).toLocaleDateString():'—';const root=$('#pages');root.innerHTML=state.pages.length?'':'<div class="empty">这个项目还没有页面</div>';for(const page of state.pages){const pending=page.latestVersion!==page.publishedVersion;const item=document.createElement('article');item.className='page';item.innerHTML=`<div><div class="page-title-line"><h3>${esc(page.title)}</h3><span class="release-status ${page.publishedVersion?'published':'draft'}">${page.publishedVersion?(pending?'有待发布版本':'已发布'):'仅预览'}</span></div><div class="meta">${esc(page.slug)} · v${page.versionCount} · ${(page.size/1024).toFixed(1)} KB · ${new Date(page.updatedAt).toLocaleString()}</div></div><div class="actions"><a href="${esc(page.latestPreviewUrl)}" target="_blank" rel="noopener">预览</a>${page.publishedVersion?`<a href="${esc(page.url)}" target="_blank" rel="noopener">线上</a>`:''}${pending||!page.publishedVersion?'<button class="publish-version">正式发布</button>':''}<button class="versions">版本</button><button class="delete">删除</button></div>`;item.querySelector('.publish-version')?.addEventListener('click',()=>publishPage(page,page.latestVersion));item.querySelector('.versions').onclick=()=>openVersions(page);item.querySelector('.delete').onclick=async()=>{if(!confirm(`确认删除“${page.title}”及其全部版本？`))return;try{await api(`${pageEndpoint()}/${page.slug}`,{method:'DELETE'});await loadPages();}catch(error){alert(error.message);}};root.append(item);}}
async function uploadPage(){const file=$('#file').files[0];if(!file)return message('请选择 HTML 文件','error');const form=new FormData();form.append('file',file);form.append('slug',$('#slug').value.trim());form.append('title',$('#title').value.trim());$('#upload').disabled=true;message('正在生成预览…');try{const page=await api(pageEndpoint(),{method:'POST',body:form});message(`预览版本 v${page.versionCount} 已生成，请预览后正式发布`,'success');window.open(page.latestPreviewUrl,'_blank','noopener');$('#slug').value='';$('#title').value='';$('#file').value='';$('#drop strong').textContent='拖入 AI 生成的 HTML';await loadPages();}catch(error){message(error.message,'error');}finally{$('#upload').disabled=false;}}
async function publishPage(page,version){if(!confirm(`确认将“${page.title}”的这个版本切换为正式线上版本？`))return;try{await api(`${pageEndpoint()}/${page.slug}/publish`,{method:'POST',json:true,body:JSON.stringify({version})});await loadPages();message('正式版本已切换','success');}catch(error){alert(error.message);}}
async function openVersions(page){try{const data=await api(`${pageEndpoint()}/${page.slug}/versions`);const rows=data.versions.map(version=>`<div class="version-row"><div><strong>v${version.number} · ${esc(version.title)}</strong><div class="muted">${new Date(version.createdAt).toLocaleString()} · ${(version.size/1024).toFixed(1)} KB ${data.page.publishedVersion===version.id?'<span class="badge">当前线上</span>':''}</div></div><div class="table-actions"><a href="${esc(version.previewUrl)}" target="_blank" rel="noopener">预览</a>${data.page.publishedVersion===version.id?'':`<button type="button" class="secondary" data-switch-version="${version.id}">切换上线</button>`}</div></div>`).join('');openModal({eyebrow:'VERSION HISTORY',title:`${page.title} · 版本记录`,description:'每个版本都可独立预览，切换上线为原子操作，线上地址保持不变。',fields:rows,submit:'关闭',onSubmit:async()=>{}});document.querySelectorAll('[data-switch-version]').forEach(button=>button.onclick=async()=>{$('#modal').close();await publishPage(page,button.dataset.switchVersion);});}catch(error){alert(error.message);}}
function message(text,type=''){$('#message').textContent=text;$('#message').className=type;}

function openModal({eyebrow,title,description='',fields,submit='确认',onSubmit}){$('#modal-eyebrow').textContent=eyebrow;$('#modal-title').textContent=title;$('#modal-description').textContent=description;$('#modal-description').className='muted';$('#modal-fields').innerHTML=fields;$('#modal-submit').textContent=submit;$('#modal-submit').type='submit';$('#modal-submit').hidden=false;$('#modal-cancel').textContent='取消';const dialog=$('#modal');dialog.showModal();$('#modal-form').onsubmit=async event=>{event.preventDefault();$('#modal-submit').disabled=true;try{const close=await onSubmit(new FormData(event.currentTarget));if(close!==false)dialog.close();}catch(error){$('#modal-description').textContent=error.message;$('#modal-description').className='error';}finally{$('#modal-submit').disabled=false;}};}
function createWorkspace(){const returnToManagement=!$('#management-view').hidden&&$('#manage-workspaces').classList.contains('active');openModal({eyebrow:'NEW WORKSPACE',title:'创建工作空间',description:'工作空间是项目、成员和 API Token 的权限边界。',fields:'<label>名称<input name="name" required placeholder="产品团队"></label><label>标识<input name="slug" required placeholder="product-team" pattern="[a-z0-9-]+"></label>',submit:'创建空间',onSubmit:async form=>{await api('/api/workspaces',{method:'POST',json:true,body:JSON.stringify({name:form.get('name'),slug:form.get('slug')})});state.workspace=null;await loadWorkspaces();if(returnToManagement)await renderWorkspaceManagement();}});bindSlugFields();}
function createProject(){if(!state.workspace)return createWorkspace();openModal({eyebrow:'NEW PROJECT',title:'创建项目',description:`项目将创建在 ${state.workspace.name} 中。`,fields:'<label>项目名称<input name="name" required placeholder="品牌官网"></label><label>项目标识<input name="slug" required placeholder="brand-site" pattern="[a-z0-9-]+"></label><label>项目说明<textarea name="description" rows="3" placeholder="这个项目负责什么？"></textarea></label>',submit:'创建项目',onSubmit:async form=>{const project=await api(`/api/workspaces/${state.workspace.slug}/projects`,{method:'POST',json:true,body:JSON.stringify(Object.fromEntries(form))});state.project=project;await loadProjects();}});bindSlugFields();}
function bindSlugFields(){const name=$('#modal-fields input[name=name]'),slug=$('#modal-fields input[name=slug]');name.oninput=()=>{if(!slug.dataset.edited)slug.value=slugify(name.value);};slug.oninput=()=>slug.dataset.edited='true';}

async function manageUsers(){
  const data=await api('/api/users');const rows=data.users.map(user=>`<div class="management-row"><div><strong>${esc(user.name)}</strong><span class="badge">${user.role==='platform_admin'?'管理员':'成员'}</span><div class="muted">@${esc(user.username)} · ${user.status==='active'?'正常':'已停用'}</div></div><button type="button" data-edit-user="${user.id}">编辑</button></div>`).join('');
  openModal({eyebrow:'PEOPLE & ROLES',title:'用户与平台角色',description:'平台管理员可管理所有空间；普通成员需要被授权到具体工作空间。',fields:`${rows}<label>姓名<input name="name" required></label><label>用户名<input name="username" required pattern="[a-zA-Z0-9_.-]{3,40}"></label><label>邮箱<input name="email" type="email"></label><label>初始密码<input name="password" type="password" minlength="10" required></label><label>平台角色<select name="role"><option value="user">普通成员</option><option value="platform_admin">平台管理员</option></select></label>`,submit:'创建用户',onSubmit:async form=>{await api('/api/users',{method:'POST',json:true,body:JSON.stringify(Object.fromEntries(form))});}});
  document.querySelectorAll('[data-edit-user]').forEach(button=>button.onclick=()=>editUser(data.users.find(user=>user.id===button.dataset.editUser)));
}
function editUser(user,returnToPage=false){openModal({eyebrow:'EDIT USER',title:`编辑 ${user.name}`,description:`@${user.username}`,fields:`<label>姓名<input name="name" value="${esc(user.name)}" required></label><label>邮箱<input name="email" type="email" value="${esc(user.email||'')}"></label><label>平台角色<select name="role"><option value="user" ${user.role==='user'?'selected':''}>普通成员</option><option value="platform_admin" ${user.role==='platform_admin'?'selected':''}>平台管理员</option></select></label><label>状态<select name="status"><option value="active" ${user.status==='active'?'selected':''}>正常</option><option value="disabled" ${user.status==='disabled'?'selected':''}>停用</option></select></label><label>重置密码 <small>留空则不修改</small><input name="password" type="password" minlength="10"></label>`,submit:'保存',onSubmit:async form=>{await api(`/api/users/${user.id}`,{method:'PATCH',json:true,body:JSON.stringify(Object.fromEntries(form))});if(returnToPage)await renderUserManagement();}});}

async function manageMembers(){
  if(!state.workspace)return;const [memberData,userData]=await Promise.all([api(`/api/workspaces/${state.workspace.slug}/members`),api(`/api/workspaces/${state.workspace.slug}/directory`)]);const members=memberData.members;
  const rows=members.map(member=>`<div class="management-row"><div><strong>${esc(member.name)}</strong><span class="badge">${roleName(member.workspaceRole)}</span><div class="muted">@${esc(member.username)}</div></div><button type="button" data-remove-member="${member.id}">移除</button></div>`).join('')||'<p class="muted">暂无成员</p>';
  const available=userData.users.filter(user=>user.status==='active'&&!members.some(member=>member.id===user.id));const options=available.map(user=>`<option value="${user.id}">${esc(user.name)} (@${esc(user.username)})</option>`).join('');
  openModal({eyebrow:'WORKSPACE ACCESS',title:`${state.workspace.name} · 成员`,description:'角色决定成员在此工作空间中可以查看、发布或管理的内容。',fields:`${rows}${available.length?`<label>添加用户<select name="userId">${options}</select></label><label>空间角色<select name="role"><option value="viewer">查看者</option><option value="editor">编辑者</option><option value="admin">空间管理员</option><option value="owner">所有者</option></select></label>`:'<p class="muted">没有更多可添加用户。平台管理员可先在“用户与角色”中创建用户。</p>'}`,submit:available.length?'授权用户':'关闭',onSubmit:async form=>{if(!available.length)return;await api(`/api/workspaces/${state.workspace.slug}/members/${form.get('userId')}`,{method:'PUT',json:true,body:JSON.stringify({role:form.get('role')})});}});
  document.querySelectorAll('[data-remove-member]').forEach(button=>button.onclick=async()=>{if(!confirm('确认移除此用户的工作空间权限？'))return;try{await api(`/api/workspaces/${state.workspace.slug}/members/${button.dataset.removeMember}`,{method:'DELETE'});$('#modal').close();await manageMembers();}catch(error){alert(error.message);}});
}
const roleName=role=>({owner:'所有者',admin:'空间管理员',editor:'编辑者',viewer:'查看者'}[role]||role);

function showManagementShell(kind){
  $('#main-topbar').hidden=true;$('#empty-state').hidden=true;$('#project-view').hidden=true;$('#management-view').hidden=false;
  document.querySelectorAll('.nav-button').forEach(button=>button.classList.toggle('active',button.id===`manage-${kind}`));
}

async function renderWorkspaceManagement(){
  const isPlatformAdmin=state.user?.role==='platform_admin';
  showManagementShell('workspaces');$('#management-eyebrow').textContent=isPlatformAdmin?'PLATFORM · WORKSPACES':'MY · WORKSPACES';$('#management-title').textContent=isPlatformAdmin?'工作空间管理':'我的工作空间';$('#management-copy').textContent=isPlatformAdmin?'拖拽调整空间顺序，管理空间名称与生命周期。空间标识创建后保持不变。':'创建自己的工作空间，并管理你拥有的空间、项目和页面。';$('#management-primary').hidden=false;$('#management-primary').textContent='新建工作空间';$('#management-primary').onclick=createWorkspace;
  const root=$('#management-content');root.innerHTML='<div class="empty">正在载入工作空间…</div>';
  try{const data=await api('/api/workspaces');state.workspaces=data.workspaces;root.innerHTML=`<div class="management-toolbar"><span><strong>${state.workspaces.length}</strong> 个工作空间</span><span class="muted">${isPlatformAdmin?'按住手柄上下拖动，松开后自动保存顺序':'你可以完整管理自己创建的空间'}</span></div><table class="data-table ${isPlatformAdmin?'sortable-table':''}"><thead><tr>${isPlatformAdmin?'<th class="sort-column" aria-label="排序"></th>':''}<th>工作空间</th><th>身份</th><th>标识</th><th>项目</th><th>更新时间</th><th></th></tr></thead><tbody id="workspace-management-list">${state.workspaces.map(workspace=>{const canManage=isPlatformAdmin||['owner','admin'].includes(workspace.currentRole),canDelete=isPlatformAdmin||workspace.currentRole==='owner';return `<tr ${isPlatformAdmin?'draggable="true"':''} data-sort-id="${workspace.slug}">${isPlatformAdmin?`<td class="sort-cell"><span class="drag-handle table-drag-handle" title="拖拽调整工作空间顺序" aria-label="拖拽调整 ${esc(workspace.name)} 的顺序">⠿</span></td>`:''}<td><strong>${esc(workspace.name)}</strong></td><td><span class="badge">${isPlatformAdmin?'平台管理员':roleName(workspace.currentRole)}</span></td><td><code>${esc(workspace.slug)}</code></td><td>${workspace.projectCount||0}</td><td>${new Date(workspace.updatedAt).toLocaleString()}</td><td><div class="table-actions">${canManage?`<button class="secondary" data-rename-workspace="${workspace.slug}">修改名称</button>`:''}${canDelete?`<button class="danger-button" data-delete-workspace="${workspace.slug}">删除</button>`:''}</div></td></tr>`;}).join('')}</tbody></table>`;
    document.querySelectorAll('[data-rename-workspace]').forEach(button=>button.onclick=()=>renameWorkspace(state.workspaces.find(workspace=>workspace.slug===button.dataset.renameWorkspace)));
    document.querySelectorAll('[data-delete-workspace]').forEach(button=>button.onclick=()=>deleteWorkspace(state.workspaces.find(workspace=>workspace.slug===button.dataset.deleteWorkspace)));
    if(isPlatformAdmin){const list=$('#workspace-management-list');enableSortable(list,'tr',async slugs=>{await api('/api/workspaces/order',{method:'PUT',json:true,body:JSON.stringify({slugs})});state.workspaces.sort((a,b)=>slugs.indexOf(a.slug)-slugs.indexOf(b.slug));renderWorkspaces();});}
  }catch(error){root.innerHTML=`<div class="empty error">${esc(error.message)}</div>`;}
}

function renameWorkspace(workspace){openModal({eyebrow:'RENAME WORKSPACE',title:'修改工作空间名称',description:`空间标识 ${workspace.slug} 和现有页面地址不会改变。`,fields:`<label>工作空间名称<input name="name" value="${esc(workspace.name)}" required maxlength="120"></label>`,submit:'保存名称',onSubmit:async form=>{await api(`/api/workspaces/${workspace.slug}`,{method:'PATCH',json:true,body:JSON.stringify({name:form.get('name')})});if(state.workspace?.slug===workspace.slug)state.workspace.name=form.get('name');await renderWorkspaceManagement();renderWorkspaces();}});}

async function deleteWorkspace(workspace){
  const confirmation=prompt(`删除“${workspace.name}”会永久删除其中所有项目和页面。\n请输入工作空间标识 ${workspace.slug} 确认：`);if(confirmation!==workspace.slug)return;
  try{await api(`/api/workspaces/${workspace.slug}`,{method:'DELETE'});if(state.workspace?.slug===workspace.slug){state.workspace=null;state.project=null;}await loadWorkspaces();await renderWorkspaceManagement();}catch(error){alert(error.message);}
}

async function renderUserManagement(){
  showManagementShell('users');$('#management-eyebrow').textContent='PLATFORM · PEOPLE';$('#management-title').textContent='用户管理';$('#management-copy').textContent='创建成员，管理账号状态与平台级角色。';$('#management-primary').hidden=false;$('#management-primary').textContent='新增用户';$('#management-primary').onclick=openCreateUser;
  const root=$('#management-content');root.innerHTML='<div class="empty">正在载入用户…</div>';
  try{const {users}=await api('/api/users');root.innerHTML=`<div class="management-toolbar"><span><strong>${users.length}</strong> 位平台用户</span><span class="muted">平台管理员可管理所有工作空间</span></div><table class="data-table"><thead><tr><th>用户</th><th>平台角色</th><th>状态</th><th>最近登录</th><th></th></tr></thead><tbody>${users.map(user=>`<tr><td><strong>${esc(user.name)}</strong><small>@${esc(user.username)}${user.email?` · ${esc(user.email)}`:''}</small></td><td><span class="badge">${user.role==='platform_admin'?'平台管理员':'普通成员'}</span></td><td><span class="status-dot ${user.status==='active'?'':'disabled'}"></span>${user.status==='active'?'正常':'已停用'}</td><td>${user.lastLoginAt?new Date(user.lastLoginAt).toLocaleString():'尚未登录'}</td><td><div class="table-actions"><button class="secondary" data-page-edit-user="${user.id}">编辑</button></div></td></tr>`).join('')}</tbody></table>`;document.querySelectorAll('[data-page-edit-user]').forEach(button=>button.onclick=()=>editUser(users.find(user=>user.id===button.dataset.pageEditUser),true));}
  catch(error){root.innerHTML=`<div class="empty error">${esc(error.message)}</div>`;}
}

function openCreateUser(){openModal({eyebrow:'NEW USER',title:'新增平台用户',description:'创建后，可在权限管理中将用户授权到工作空间。',fields:'<label>姓名<input name="name" required></label><label>用户名<input name="username" required pattern="[a-zA-Z0-9_.-]{3,40}"></label><label>邮箱<input name="email" type="email"></label><label>初始密码<input name="password" type="password" minlength="10" required></label><label>平台角色<select name="role"><option value="user">普通成员</option><option value="platform_admin">平台管理员</option></select></label>',submit:'创建用户',onSubmit:async form=>{await api('/api/users',{method:'POST',json:true,body:JSON.stringify(Object.fromEntries(form))});await renderUserManagement();}});}

async function renderAccessManagement(){
  showManagementShell('access');$('#management-eyebrow').textContent='WORKSPACE · RBAC';$('#management-title').textContent='权限管理';$('#management-copy').textContent='按工作空间分配成员角色和访问范围。';$('#management-primary').hidden=false;$('#management-primary').textContent='授权用户';$('#management-primary').onclick=()=>openGrantMember();
  const root=$('#management-content');if(!state.workspace){root.innerHTML='<div class="empty">请先创建工作空间</div>';$('#management-primary').hidden=true;return;}root.innerHTML='<div class="empty">正在载入权限…</div>';
  try{const {members}=await api(`/api/workspaces/${state.workspace.slug}/members`);root.innerHTML=`<div class="management-toolbar"><label>工作空间<select id="access-workspace">${state.workspaces.map(workspace=>`<option value="${workspace.slug}" ${workspace.slug===state.workspace.slug?'selected':''}>${esc(workspace.name)}</option>`).join('')}</select></label><span class="muted">${members.length} 位已授权成员</span></div><div class="role-card-grid"><div class="role-card"><strong>所有者</strong><small>完整管理权限</small></div><div class="role-card"><strong>空间管理员</strong><small>成员、项目和 Token</small></div><div class="role-card"><strong>编辑者</strong><small>发布和管理页面</small></div><div class="role-card"><strong>查看者</strong><small>只读访问内容</small></div></div><table class="data-table"><thead><tr><th>成员</th><th>空间角色</th><th>加入时间</th><th></th></tr></thead><tbody>${members.map(member=>`<tr><td><strong>${esc(member.name)}</strong><small>@${esc(member.username)}</small></td><td><select data-member-role="${member.id}">${['owner','admin','editor','viewer'].map(role=>`<option value="${role}" ${member.workspaceRole===role?'selected':''}>${roleName(role)}</option>`).join('')}</select></td><td>${new Date(member.joinedAt).toLocaleDateString()}</td><td><div class="table-actions"><button class="secondary" data-save-role="${member.id}">保存</button><button class="danger-button" data-remove-access="${member.id}">移除</button></div></td></tr>`).join('')}</tbody></table>`;
    $('#access-workspace').onchange=async event=>{state.workspace=state.workspaces.find(workspace=>workspace.slug===event.target.value);state.project=null;await loadProjects();await renderAccessManagement();};
    document.querySelectorAll('[data-save-role]').forEach(button=>button.onclick=async()=>{const role=document.querySelector(`[data-member-role="${button.dataset.saveRole}"]`).value;try{await api(`/api/workspaces/${state.workspace.slug}/members/${button.dataset.saveRole}`,{method:'PUT',json:true,body:JSON.stringify({role})});button.textContent='已保存';setTimeout(()=>button.textContent='保存',1200);}catch(error){alert(error.message);}});
    document.querySelectorAll('[data-remove-access]').forEach(button=>button.onclick=async()=>{if(!confirm('确认移除此用户的工作空间权限？'))return;try{await api(`/api/workspaces/${state.workspace.slug}/members/${button.dataset.removeAccess}`,{method:'DELETE'});await renderAccessManagement();}catch(error){alert(error.message);}});
  }catch(error){root.innerHTML=`<div class="empty error">${esc(error.message)}</div>`;}
}

async function openGrantMember(){
  const [memberData,userData]=await Promise.all([api(`/api/workspaces/${state.workspace.slug}/members`),api(`/api/workspaces/${state.workspace.slug}/directory`)]);const available=userData.users.filter(user=>!memberData.members.some(member=>member.id===user.id));
  if(!available.length){alert('没有可授权的新用户，请先创建用户。');return;}
  openModal({eyebrow:'GRANT ACCESS',title:`授权到 ${state.workspace.name}`,description:'选择用户及其在该工作空间中的角色。',fields:`<label>用户<select name="userId">${available.map(user=>`<option value="${user.id}">${esc(user.name)} (@${esc(user.username)})</option>`).join('')}</select></label><label>空间角色<select name="role"><option value="viewer">查看者</option><option value="editor">编辑者</option><option value="admin">空间管理员</option><option value="owner">所有者</option></select></label>`,submit:'确认授权',onSubmit:async form=>{await api(`/api/workspaces/${state.workspace.slug}/members/${form.get('userId')}`,{method:'PUT',json:true,body:JSON.stringify({role:form.get('role')})});await renderAccessManagement();}});
}

const scopeLabel=scopes=>scopes.includes('admin')?'管理员':scopes.includes('write')?'读取 + 发布':'只读';
async function renderTokenManagement(){
  if(!state.workspace){alert('请先选择工作空间');return;}showManagementShell('tokens-page');$('#management-eyebrow').textContent='WORKSPACE · API ACCESS';$('#management-title').textContent='API Token';$('#management-copy').textContent=`管理 ${state.workspace.name} 的 AI Agent、CLI 和 CI/CD 访问凭证。`;$('#management-primary').hidden=false;$('#management-primary').textContent='创建 Token';$('#management-primary').onclick=openCreateToken;
  const root=$('#management-content');root.innerHTML='<div class="empty">正在载入 Token…</div>';
  try{const {tokens}=await api(`/api/workspaces/${state.workspace.slug}/tokens`);root.innerHTML=`<div class="management-toolbar"><label>工作空间<select id="token-workspace">${state.workspaces.map(workspace=>`<option value="${workspace.slug}" ${workspace.slug===state.workspace.slug?'selected':''}>${esc(workspace.name)}</option>`).join('')}</select></label><span class="muted">密钥明文只在创建或重置时显示一次</span></div><table class="data-table"><thead><tr><th>名称</th><th>Token 前缀</th><th>权限</th><th>最后使用</th><th>状态</th><th></th></tr></thead><tbody>${tokens.map(token=>`<tr><td><strong>${esc(token.name)}</strong><small>${new Date(token.createdAt).toLocaleDateString()} 创建</small></td><td><code>${esc(token.prefix)}••••••</code></td><td><span class="badge">${scopeLabel(token.scopes)}</span></td><td>${token.lastUsedAt?new Date(token.lastUsedAt).toLocaleString():'从未使用'}</td><td><span class="status-dot ${token.revokedAt?'disabled':''}"></span>${token.revokedAt?'已吊销':token.expiresAt&&new Date(token.expiresAt)<new Date()?'已过期':'有效'}</td><td><div class="table-actions"><button class="secondary" data-view-token="${token.id}">查看</button>${token.revokedAt?'':`<button class="secondary" data-reset-token="${token.id}">重置</button><button class="danger-button" data-revoke-token="${token.id}">吊销</button>`}</div></td></tr>`).join('')||'<tr><td colspan="6"><div class="empty">还没有 API Token</div></td></tr>'}</tbody></table>`;
    $('#token-workspace').onchange=async event=>{state.workspace=state.workspaces.find(workspace=>workspace.slug===event.target.value);state.project=null;syncWorkspaceTools();await renderTokenManagement();};
    document.querySelectorAll('[data-view-token]').forEach(button=>button.onclick=()=>viewToken(tokens.find(token=>token.id===button.dataset.viewToken)));
    document.querySelectorAll('[data-reset-token]').forEach(button=>button.onclick=()=>resetToken(tokens.find(token=>token.id===button.dataset.resetToken)));
    document.querySelectorAll('[data-revoke-token]').forEach(button=>button.onclick=()=>revokeToken(tokens.find(token=>token.id===button.dataset.revokeToken)));
  }catch(error){root.innerHTML=`<div class="empty error">${esc(error.message)}</div>`;}
}

function openCreateToken(){openModal({eyebrow:'NEW API TOKEN',title:'创建 API Token',description:`密钥仅用于 ${state.workspace.name}，创建后只显示一次。`,fields:'<label>Token 名称<input name="name" required placeholder="AI 发布助手"></label><label>权限<select name="scope"><option value="writer">读取 + 发布</option><option value="reader">只读</option><option value="admin">空间管理员</option></select></label>',submit:'创建 Token',onSubmit:async form=>{const scopes=form.get('scope')==='admin'?['admin']:form.get('scope')==='reader'?['read']:['read','write'];const result=await api(`/api/workspaces/${state.workspace.slug}/tokens`,{method:'POST',json:true,body:JSON.stringify({name:form.get('name'),scopes})});showTokenSecret(result.secret,'Token 创建成功');return false;}});}
function viewToken(token){openModal({eyebrow:'TOKEN DETAILS',title:token.name,description:'出于安全原因，平台不保存可找回的密钥明文。若密钥丢失，请执行重置。',fields:`<div class="token-detail-grid"><span>Token 前缀</span><strong><code>${esc(token.prefix)}••••••</code></strong><span>权限</span><strong>${scopeLabel(token.scopes)}</strong><span>创建时间</span><strong>${new Date(token.createdAt).toLocaleString()}</strong><span>最后使用</span><strong>${token.lastUsedAt?new Date(token.lastUsedAt).toLocaleString():'从未使用'}</strong><span>有效期</span><strong>${token.expiresAt?new Date(token.expiresAt).toLocaleString():'长期有效'}</strong><span>状态</span><strong>${token.revokedAt?'已吊销':'有效'}</strong></div>`,submit:'关闭',onSubmit:async()=>{}});}
async function resetToken(token){if(!confirm(`确认重置“${token.name}”？旧密钥会立即失效。`))return;try{const result=await api(`/api/workspaces/${state.workspace.slug}/tokens/${token.id}/reset`,{method:'POST'});showTokenSecret(result.secret,'Token 已重置');}catch(error){alert(error.message);}}
async function revokeToken(token){if(!confirm(`确认吊销“${token.name}”？吊销后无法恢复。`))return;try{await api(`/api/workspaces/${state.workspace.slug}/tokens/${token.id}`,{method:'DELETE'});await renderTokenManagement();}catch(error){alert(error.message);}}

async function manageTokens(){if(!state.workspace)return;const data=await api(`/api/workspaces/${state.workspace.slug}/tokens`);const rows=data.tokens.map(token=>`<div class="token-row"><div><strong>${esc(token.name)}</strong><div class="muted">${esc(token.prefix)}… · ${token.scopes.join(', ')}${token.revokedAt?' · 已吊销':''}</div></div>${token.revokedAt?'':`<button type="button" data-revoke="${token.id}">吊销</button>`}</div>`).join('')||'<p class="muted">还没有 API Token。</p>';openModal({eyebrow:'AI & AUTOMATION',title:'API Token',description:'为 AI Agent 或 CI 创建独立密钥。密钥仅显示一次。',fields:`${rows}<label>Token 名称<input name="name" required placeholder="AI 发布助手"></label><label>权限<select name="scope"><option value="writer">读取 + 发布</option><option value="reader">只读</option><option value="admin">管理员</option></select></label>`,submit:'创建 Token',onSubmit:async form=>{const scopes=form.get('scope')==='admin'?['admin']:form.get('scope')==='reader'?['read']:['read','write'];const result=await api(`/api/workspaces/${state.workspace.slug}/tokens`,{method:'POST',json:true,body:JSON.stringify({name:form.get('name'),scopes})});showTokenSecret(result.secret);return false;}});document.querySelectorAll('[data-revoke]').forEach(button=>button.onclick=async()=>{if(!confirm('吊销后无法恢复，确认继续？'))return;await api(`/api/workspaces/${state.workspace.slug}/tokens/${button.dataset.revoke}`,{method:'DELETE'});$('#modal').close();await manageTokens();});}
function showTokenSecret(secret,title='Token 创建成功'){$('#modal-eyebrow').textContent='SECRET · SHOW ONCE';$('#modal-title').textContent=title;$('#modal-description').textContent='请立即复制并保存。关闭窗口后无法再次查看。';$('#modal-fields').innerHTML=`<div class="secret">${esc(secret)}</div><button id="copy-secret" type="button" class="secondary copy-secret">复制密钥</button>`;$('#copy-secret').onclick=async()=>{await navigator.clipboard.writeText(secret);$('#copy-secret').textContent='已复制';};$('#modal-submit').textContent='我已安全保存';$('#modal-form').onsubmit=event=>{event.preventDefault();$('#modal').close();renderTokenManagement();};}

$('#refresh').onclick=loadWorkspaces;$('#new-workspace').onclick=createWorkspace;$('#new-project').onclick=createProject;$('#home-new-project').onclick=createProject;$('#workspace-members').onclick=()=>manageMembers().catch(error=>alert(error.message));$('#manage-tokens-page').onclick=renderTokenManagement;$('#manage-workspaces').onclick=renderWorkspaceManagement;$('#manage-users').onclick=renderUserManagement;$('#manage-access').onclick=renderAccessManagement;$('#upload').onclick=uploadPage;$('#modal-close').onclick=$('#modal-cancel').onclick=()=>$('#modal').close();
const drop=$('#drop'),fileInput=$('#file');fileInput.onchange=()=>{if(fileInput.files[0])drop.querySelector('strong').textContent=fileInput.files[0].name;};for(const event of ['dragenter','dragover'])drop.addEventListener(event,e=>{e.preventDefault();drop.classList.add('drag');});for(const event of ['dragleave','drop'])drop.addEventListener(event,e=>{e.preventDefault();drop.classList.remove('drag');});drop.addEventListener('drop',e=>{fileInput.files=e.dataTransfer.files;fileInput.onchange();});
init();
